// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXjqAGOaP9OxWGyDpKCO5iMweE4jTbwkU',
    appId: '1:831580654920:web:9ab72bdf5287dc924df77d',
    messagingSenderId: '831580654920',
    projectId: 'dots-and-boxes-65ef1',
    authDomain: 'dots-and-boxes-65ef1.firebaseapp.com',
    databaseURL: 'https://dots-and-boxes-65ef1-default-rtdb.firebaseio.com',
    storageBucket: 'dots-and-boxes-65ef1.firebasestorage.app',
    measurementId: 'G-HMP8YY1PPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYV6rvEGPWtq68nVWIjXbH6-Wruyv8sI',
    appId: '1:831580654920:android:ea031e0fe6fa32ae4df77d',
    messagingSenderId: '831580654920',
    projectId: 'dots-and-boxes-65ef1',
    databaseURL: 'https://dots-and-boxes-65ef1-default-rtdb.firebaseio.com',
    storageBucket: 'dots-and-boxes-65ef1.firebasestorage.app',
  );

}